<main role="main"><center>
  <div class="container"><br>
    <h3><strong>Installation d'un serveur web Nginx</strong></h3>
    <a href="../controller/redirection.php?enter=tools" class="btn btn-success my-2">Boite a outils</a>
    <a href="../controller/redirection.php?enter=servers" class="btn btn-primary my-2">Gestion de serveur(s) Debian 9</a><br><br>
  </div>
  <section class="jumbotron ">
    <div class="ml-2">

<?php
#-------------------------------------------------------------------------------
# GENERATION DU SCRIPT D'INSTALLATION DE NGINX
#-------------------------------------------------------------------------------

#GÉNÉRATION DES VARIABLE DE FICHIERS--------------------------------------------
$file_path="../script/script_client/install_nginx_".session_id().".sh";
$file_name="install_nginx.sh";

#AJOUT DU LIEN DE TÉLÉCHARGEMENT & GUIDE----------------------------------------
include("../view/guide_execution_server_web_nginx.php");
echo "<center><a class='btn btn-danger' href='".$file_path."'download='".$file_name."' target='_blank'>Télécharger le script d'installation </a></center><br>";

#-------------------------------------------------------------------------------
# GÉNÉRATION DU SCRIPT
#-------------------------------------------------------------------------------
if(isset($_GET['action']) && isset($_GET['under_action'])){
    #CREATION DE VARIABLE D'ISOLEMENT
    $nginx='"dpkg -l | grep nginx"';
    #GÉNÉRATION DU SCRIPT-------------------------------------------------------
    $firstline = "
    #!/bin/bash
    #---------------------------------------------------------------------------
    #SCRIPT D'INSTALLATION D'NGINX généré par IpSpawn.com
    #---------------------------------------------------------------------------\n";

    $script="

    apt install nginx -y
    apt install php-fpm -y
    apt install php -y
    apt install mariadb-server -y

    echo '
##\n
# You should look at the following URL's in order to grasp a solid understanding\n
# of Nginx configuration files in order to fully unleash the power of Nginx.\n
# http://wiki.nginx.org/Pitfalls\n
# http://wiki.nginx.org/QuickStart\n
# http://wiki.nginx.org/Configuration\n
#\n
# Generally, you will want to move this file somewhere, and start with a clean\n
# file but keep this around for reference. Or just disable in sites-enabled.\n
#\n
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.\n
##\n
\n
# Default server configuration\n
#\n
server {\n
        listen 80 default_server;\n
        listen [::]:80 default_server;\n
\n
        # SSL configuration\n
        #\n
        # listen 443 ssl default_server;\n
        # listen [::]:443 ssl default_server;\n
        #\n
        # Note: You should disable gzip for SSL traffic.\n
        # See: https://bugs.debian.org/773332\n
        #\n
        # Read up on ssl_ciphers to ensure a secure configuration.\n
        # See: https://bugs.debian.org/765782\n
        #\n
        # Self signed certs generated by the ssl-cert package\n
        # Don't use them in a production server!\n
        #\n
        # include snippets/snakeoil.conf;\n
\n
        root /var/www/html;\n
\n
        # Add index.php to the list if you are using PHP\n
        index index.php index.html index.htm index.nginx-debian.html;\n
\n
        server_name _;\n
\n
        location / {\n
                # First attempt to serve request as file, then\n
                # as directory, then fall back to displaying a 404.\n
                try_files $uri $uri/ =404;\n
	        # proxy_pass http://localhost:8080;\n
        	# proxy_http_version 1.1;\n
	        # proxy_set_header Upgrade $http_upgrade;\n
        	# proxy_set_header Connection 'upgrade';\n
	        # proxy_set_header Host $host;\n
        	# proxy_cache_bypass $http_upgrade;\n
        }\n
\n
        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000\n
        #\n
        location ~ \.php$ {\n
               include snippets/fastcgi-php.conf;\n
        #\n
        #       # With php7.0-cgi alone:\n
        #       fastcgi_pass 127.0.0.1:9000;\n
        #       # With php7.0-fpm:\n
               fastcgi_pass unix:/run/php/php7.0-fpm.sock;\n
        }\n
\n
        # deny access to .htaccess files, if Apache's document root\n
        # concurs with nginx's one\n
        #\n
        #location ~ /\.ht {\n
        #       deny all;\n
        #}\n
}\n
\n
\n
# Virtual Host configuration for example.com\n
#\n
# You can move that to a different file under sites-available/ and symlink that\n
# to sites-enabled/ to enable it.\n
#\n
#server {\n
#       listen 80;\n
#       listen [::]:80;\n
#\n
#       server_name example.com;\n
#\n
#       root /var/www/example.com;\n
#       index index.html;\n
#\n
#       location / {\n
#               try_files $uri $uri/ =404;\n
#       }\n
#}' > /etc/nginx/sites_available/default
service nginx restart
    ";

    #RASSEMBLEMENT DES VARIABLES & CREATION DU SCRIPT-------------------------
    $new_script = $firstline . $script ;
    $file = fopen($file_path, 'w+');
    fputs($file,$new_script);

  }
?>
    </div>
  </section>
</main>
